# Trestle demonstration workflow

name: trestle pr validation pipeline

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install trestle
      run: 
        make install
    - name: Validate trestle files
      run: |
        make test