# Workflow to release a set of assembled trestle files

name: Trestle deploy

on:
  push:
    branches:
      - main
      - develop
  schedule:
    # Run once per day to ensure we have no build failures due to dependency updates.
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 22 * * *'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install trestle
      run: 
        make install
    - name: Validate trestle files
      run: |
        make test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.ADMIN_PAT }} 
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install all tools
      run: |
        make install
    - name: Create release
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.ADMIN_PAT }}
      run: |
        make release


  merge-main-to-develop:
    name: Merge main -> develop
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}
        source-branch: main
        target-branch: develop
        commit-message: "chore: Merge back version tags and changelog into develop."

